### PR TITLE
334. Increasing Triplet Subsequence

### PR DESCRIPTION
**Pull request by Piyushjar**

### CODE REVIEW

**Comment by RajkumarSony** [comment]
Dear Contributor, 

Kindly Start ⭐ this repo. and Add your information in PARTICIPANTS.md file. After that only your PRs will be accepted. Don't avoid it.

Thank You.

**Comment by Piyushjar** [comment]
added info in participants.md and stared. Thanks

**Comment by RajkumarSony** [comment]
Repo has Conflicting files.. Request again!

**Comment by Piyushjar** [comment]
Resolved it please check. Thanks.

**Pull request merged**
