### PR TITLE
added the optimised java solution for 242

### PR DESCRIPTION
**Pull request by sarapapa-sp**

### CODE REVIEW

**Comment by sarapapa-sp** [comment]
with reference to #25 .
Optimised the solution using some default methods of Java.

**Comment by sarapapa-sp** [comment]
Added the PARTICIPANTS.md file.

**Comment by RajkumarSony** [comment]
Kindly Star ⭐ this Repo.

**Comment by sarapapa-sp** [comment]
yes i have ⭐ the repo

**Comment by RajkumarSony** [comment]
Thanks, page was not updated.

**Pull request merged**
