### PR TITLE
primeno

### PR DESCRIPTION
**Pull request by PRANAVPATIL234**

### CODE REVIEW

**Comment by RajkumarSony** [comment]
Dear Contributor, 

Kindly Start ⭐ this repo. and Add your information in PARTICIPANTS.md file. After that only your PRs will be accepted. Don't avoid it.

Thank You.

**Comment by RajkumarSony** [comment]
Dear Contributor, 

Kindly Start ⭐ this repo. and Add your information in PARTICIPANTS.md file. After that only your PRs will be accepted. Don't avoid it.

Thank You.

**Comment by RajkumarSony** [comment]
Request Again!

**Comment by PRANAVPATIL234** [comment]
Mouseactivity

**Comment by RajkumarSony** [comment]
This branch has conflicts that must be resolved
Use the web editor or the  to resolve conflicts.
Conflicting files
PARTICIPANTS.md
-----

kindly check it.

**Pull request closed without merging**
