### PR TITLE
Update PARTICIPANTS.md

### PR DESCRIPTION
**Pull request by Sam0204**

### CODE REVIEW

**Comment by RajkumarSony** [comment]
Kindly Star ⭐ this Repo.

**Comment by Sam0204** [comment]
Yes I already do that.

**Comment by RajkumarSony** [comment]
Dear Contributor,

Kindly Start ⭐ this repo. After that only your PRs will be accepted. Don't avoid it.

Thank You.

**Comment by Sam0204** [comment]
I have done both Starred and participation.md.
Please merge my request..

**Comment by Sam0204** [comment]
Please merge my another 2 pull request #40 #41  And give mi
Hacktoberfest-accepted tag

**Comment by Sam0204** [comment]
Please accept my req no#40 and #41.. and please mearged my request and give
me a tag.

**Pull request merged**
