### PR TITLE
Create Intersection_point-Linked-List.c

### PR DESCRIPTION
**Pull request by Vikash0122**
This is a good question of Linked List.

### CODE REVIEW

**Comment by RajkumarSony** [comment]
Dear Contributor, 

Kindly Start ⭐ this repo. and Add your information in PARTICIPANTS.md file. After that only your PRs will be accepted. Don't avoid it.

Thank You.

**Comment by Vikash0122** [comment]
I have updated please check

**Comment by RajkumarSony** [comment]
Kindly Star 💫  this Repo.

**Comment by Vikash0122** [comment]
I have already starred 🥲

**Pull request merged**
